# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id_number', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20)),
                ('rate_card', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=' ', max_length=3)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayDay1.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('man_id_number', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('manager', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('hours_worked', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('timesheet_approve', models.BooleanField(default=True)),
                ('job', models.ManyToManyField(to='PayDay1.Job')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ManyToManyField(to='PayDay1.Job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayDay1.Job_complete'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(default='choose manager', on_delete=django.db.models.deletion.CASCADE, to='PayDay1.Manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
