# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
