# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0002_auto_20200426_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
