# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0004_auto_20200426_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
