# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0005_auto_20200426_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 26, 21, 2, 43, 427391)),
        ),
    ]
