# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0007_auto_20200426_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
