# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0008_auto_20200428_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
