# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0020_auto_20200507_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_approve',
            field=models.BooleanField(default=False),
        ),
    ]
