# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayDay1', '0021_auto_20200507_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
